[rpc]
bind = 'tcp://127.0.0.1:5557'


[smtp]
host = "127.0.0.1"
port = "25"
user = ""
password = ""


[mailbox]

  [mailbox.notifier]
    key = "notifier"
    emitter = "notifier@certifarm.org"
    mailbox = "/tmp/certifarm"


[logging]
  version = 1
  disable_existing_loggers = true

  [logging.formatters]
    [logging.formatters.standard]
      format = '%(asctime)s [%(levelname)s] %(name)s: %(message)s'

  [logging.handlers]
     [logging.handlers.default]
       level = "INFO"
       formatter = "standard"
       class = "logging.StreamHandler"
       stream = "ext://sys.stdout"

  [logging.loggers]
    [logging.loggers.""]
      handlers= ['default']
      level = 'WARNING'
      propagate = false

    [logging.loggers.microfarm_courrier]
      handlers = ["default"]
      level = "DEBUG"
      propagate = false
